###################################################################################################
####                                Index limit 30
[Command 1]
Name=✅ Headset connect
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/headset_connect.sh
Icon=
[Command 2]
Name=❌ Headset disconnect
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/headset_disconnect.sh
Icon=

###################################################################################################

[Command 5]
Name=✅ Night Light On
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/night_light_on.sh
Icon=
[Command 6]
Name=❌ Night Light Off
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/night_light_off.sh
Icon=

###################################################################################################

[Command 8]
Name=🌐 Internet refresh
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/internet_refresh.sh
Icon=

###################################################################################################

[Command 11]
Name=🎙️ Mute toggle
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/microphone_toggle.sh
Icon=

###################################################################################################

[Command 15]
Name=🍃 GPU Fan Speed 35%
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_35.sh
Icon=

[Command 16]
Name=🌬️ GPU Fan Speed 50%
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_50.sh
Icon=


[Command 17]
Name=🌪️ GPU Fan Speed 75%
Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_75.sh
Icon=

#####[Command 18]
#####Name=🌪️ GPU Fan Speed 100%
#####Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_100.sh
#####Icon=

##### [Command 19]
##### Name=🔥 GPU Fan Speed AUTO
##### Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_0_AUTO.sh
##### Icon=

##### [Command 20]
##### Name=🔥 GPU Fan OFF
##### Command=$HOME/Nextcloud/Linux/scripts/Shortcuts/GPU_fan_speed/gpu_fan_speed_0_OFF.sh
##### Icon=

###################################################################################################
